
appname = API_CRUD_TIENDA
httpport = ${API_CRUD_HTTP_PORT}
runmode = ${API_CRUD_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

#definicion de variables de entorno db

PGuser = ${API_CRUD_DB_USER}
PGpassword = ${API_CRUD_DB_PASSWORD}
PGhost = ${API_CRUD_DB_HOST}
PGport = ${API_CRUD_DB_PORT}
PGdatabase = ${API_CRUD_TIENDA_PGDB}
PGschema = ${API_CRUD_TIENDA_PGDSHEMA}
