#appname = Core_api
#httpport = 8080
#runmode = dev
#autorender = false
#copyrequestbody = true
#EnableDocs = true
#sqlconn = postgres://postgres:postgres@127.0.0.1:5432/jobsy_api?sslmode=disable



# _HTTP_PORT= [Puerto de exposición del api]
# _RUN_MODE= [Modo de ejecución del API: dev]
# _Variables de la DB
# _PGUSER = [Usuario de DB] 
# _PGPASS = [Contraseña del usuario de DB]
# _PGHOST = [URL, IP, DOMINIO o EMPOINT de la DB]
# _PGPORT = [Puerto de la DB]
# _PGDATABASE = [Nombre de la DB]
# _PGSCHEMA = [Nombre del esquema de la base de datos




appname = core_api
httpport = ${CORE_API_HTTP_PORT}
runmode = ${CORE_API_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

#Definicion de variables de entorno para la conexión a la base de datos


PGuser=${CORE_API_PGUSER}
PGpass=${CORE_API_PGPASS}
PGhost=${CORE_API_PGHOST}
PGport=${CORE_API_PGPORT}
PGdatabase=${CORE_API_PGDATABASE}
PGschema=${CORE_API_PGSCHEMA}





# export API_CRUD_TIENDA_HTTP_PORT=8080 && \
# export API_CRUD_TIENDA_PGUSER=postgres && \
# export API_CRUD_TIENDA_RUN_MODE=dev && \
# export API_CRUD_TIENDA_PGPASS=postgres && \
# export API_CRUD_TIENDA_PGHOST=localhost && \
# export API_CRUD_TIENDA_PGPORT=5432 && \
# export API_CRUD_TIENDA_PGDATABASE=tienda_db && \
# export API_CRUD_TIENDA_PGSCHEMA=pedidos