appname = Soporte_API
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:10291029@127.0.0.1:5432/Jobsy?sslmode=disable&search_path=soporte
