# Variables de API
# _HTTP_PORT = [Puerto de expocion del api]
# _RUNMODE = [Modo de ejecucion del API: dev, prod, test]

# Variables de BD 
# _PGUSER = [Usuario de BD]
# _PGPASSWORD = [Password de BD]
# _PGHOST = [IP, URL, DOMINIO o ENDPOINT de BD]
# _PGPORT = [Puerto de la BD]
# _PGDATABASE = [Nombre de la BD]
# _PGSCHEMA = [Esquema de la BD]

appname         = Crud_soporte
httpport        = ${CRUD_SOPORTE_HTTP_PORT}
runmode         = ${CRUD_SOPORTE_RUNMODE}
autorender      = false
copyrequestbody = true
EnableDocs      = true

#Definicion de variables de entorno DB
PGuser      = ${CRUD_SOPORTE_PGUSER}
PGpassword  = ${CRUD_SOPORTE_PGPASSWORD}
PGhost      = ${CRUD_SOPORTE_PGHOST}
PGport      = ${CRUD_SOPORTE_PGPORT}
PGdatabase  = ${CRUD_SOPORTE_PGDATABASE}
PGschema    = ${CRUD_SOPORTE_PGSCHEMA}

