appname         = api_crud_tienda
httpport        = ${CRUD_TIENDA_HTTP_PORT}
runmode         = ${CRUD_TIENDA_RUNMODE}
autorender      = false
copyrequestbody = true
EnableDocs      = true

# Definición de variables de entorno DB
PGuser          = ${CRUD_TIENDA_PGUSER}
PGpassword      = ${CRUD_TIENDA_PGPASSWORD}
PGhost          = ${CRUD_TIENDA_PGHOST}
PGport          = ${CRUD_TIENDA_PGPORT}
PGdatabase      = ${CRUD_TIENDA_PGDATABASE}
Pgschema        = ${CRUD_TIENDA_PGSCHEMA}